filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    symlinks: true

processors:
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
