services:
  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - "6379:6379"
    networks:
      - finstant-network
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - finstant-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - finstant-network

  finanstream:
    build:
      context: ./FinanStream
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./config/rates.properties:/app/rates.properties
    environment:
      - RATES_CONFIG_PATH=file:/app/rates.properties
      - FINANSTREAM_PLATFORMS_PLATFORM1_HOST=platform1
      - FINANSTREAM_PLATFORMS_PLATFORM2_HOST=platform2
      - SPRING_DATA_REDIS_HOST=redis
    networks:
      - finstant-network

  platform1_telnet:
    container_name: platform1
    build:
      context: ./Platform1_Telnet
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - finstant-network

  platform2_rest:
    container_name: platform2
    build:
      context: ./Platform2_REST
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - finstant-network

networks:
  finstant-network:
    driver: bridge